import sys

OUT = 'backend/Filamorfosis.Tests/MaterialSupplyCostModelPropertyTests.cs'
L = []
def a(s): L.append(s)

a('// Feature: material-supply-cost-model, Property 1: Material base cost equals sum of supply usage products')
a('// Feature: material-supply-cost-model, Property 2: Material base cost response is consistent with returned supply usages')
a('// Feature: material-supply-cost-model, Property 3: Full price formula holds for any valid variant inputs')
a('// Feature: material-supply-cost-model, Property 4: Replace-all semantics for usage persistence')
a('// Feature: material-supply-cost-model, Property 5: Non-positive quantities are always rejected')
a('// Feature: material-supply-cost-model, Property 6: Unknown reference IDs are always rejected')
a('// Feature: material-supply-cost-model, Property 7: Cascade delete removes all child usage rows')
a('// Feature: material-supply-cost-model, Property 8: Variant stock is in-stock iff all material stock quantities are positive')
a('// Feature: material-supply-cost-model, Property 9: CostParameter update propagates to all referencing materials')
a('// Feature: material-supply-cost-model, Property 10: Deleting a material referenced by a variant is always rejected')
a('')
a('using System.Net;')
a('using System.Net.Http.Json;')
a('using Filamorfosis.Application.DTOs;')
a('using Filamorfosis.Application.Services;')
a('using Filamorfosis.Domain.Entities;')
a('using Filamorfosis.Infrastructure.Data;')
a('using Filamorfosis.Infrastructure.Services;')
a('using Filamorfosis.Tests.Infrastructure;')
a('using FsCheck;')
a('using FsCheck.Fluent;')
a('using FsCheck.Xunit;')
a('using Microsoft.EntityFrameworkCore;')
a('using Microsoft.Extensions.DependencyInjection;')
a('')
a('namespace Filamorfosis.Tests;')
a('')
a('public class MaterialSupplyCostModelPropertyTests')
a('{')
a('    private static Gen<decimal> NonNegCostGen =>')
a('        Gen.Choose(0, 10000).Select(i => (decimal)i / 100m);')
a('')
a('    private static Gen<decimal> PosCostGen =>')
a('        Gen.Choose(1, 10000).Select(i => (decimal)i / 100m);')
a('')
a('    private static Gen<decimal> TaxRateGen =>')
a('        Gen.Choose(0, 100).Select(i => (decimal)i / 100m);')
a('')
a('    private static Gen<int> ManufactureTimeGen =>')
a('        Gen.Choose(0, 480);')
a('')
a('    private static Gen<decimal> ElectricRateGen =>')
a('        Gen.Choose(0, 1000).Select(i => (decimal)i / 100m);')
a('')
a('    private static FilamorfosisDbContext CreateInMemoryDb(string dbName)')
a('    {')
a('        var options = new DbContextOptionsBuilder<FilamorfosisDbContext>()')
a('            .UseInMemoryDatabase(dbName)')
a('            .Options;')
a('        return new FilamorfosisDbContext(options);')
a('    }')
a('')
a('    private static PricingCalculatorService CreatePricingService(FilamorfosisDbContext db)')
a('        => new(db);')
a('')
# Property 1 - pure unit test
a('    // Feature: material-supply-cost-model, Property 1: Material base cost equals sum of supply usage products')
a('    // Validates: Requirements 2.1, 2.4')
a('    [Fact]')
a('    public void Property1_MaterialBaseCostEqualsSumOfSupplyUsageProducts()')
a('    {')
a('        var db = CreateInMemoryDb(nameof(Property1_MaterialBaseCostEqualsSumOfSupplyUsageProducts));')
a('        var svc = CreatePricingService(db);')
a('')
a('        var pairGen =')
a('            from unitCost in NonNegCostGen')
a('            from qty in NonNegCostGen')
a('            select (unitCost, qty);')
a('')
a('        var listGen = Gen.Choose(0, 5).SelectMany(n => pairGen.ListOf(n));')
a('')
a('        Prop.ForAll(Arb.From(listGen), usages =>')
a('        {')
a('            var expected = usages.Sum(u => u.unitCost * u.qty);')
a('            var actual = svc.ComputeMaterialBaseCost(usages.Select(u => (u.unitCost, u.qty)));')
a('            return actual == expected;')
a('        })')
a('        .QuickCheckThrowOnFailure();')
a('')
a('        Assert.Equal(0m, svc.ComputeMaterialBaseCost([]));')
a('    }')
a('')
# Property 2 - integration test
a('    // Feature: material-supply-cost-model, Property 2: Material base cost response is consistent with returned supply usages')
a('    // Validates: Requirements 2.3, 2.5')
a('    [Property(MaxTest = 20)]')
a('    public Property Property2_MaterialBaseCostResponseConsistentWithSupplyUsages()')
a('    {')
a('        var pairGen =')
a('            from unitCost in PosCostGen')
a('            from qty in PosCostGen')
a('            select (unitCost, qty);')
a('')
a('        var listGen = Gen.Choose(1, 3).SelectMany(n => pairGen.ListOf(n));')
a('')
a('        return Prop.ForAll(')
a('            Arb.From(listGen),')
a('            usages => RunProperty2Async(usages).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty2Async(List<(decimal unitCost, decimal qty)> usages)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        var supplyUsagesMap = new Dictionary<string, decimal>();')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category')
a('            {')
a('                Id = catId,')
a('                Slug = $"p2-cat-{catId:N}",')
a('                NameEs = "Cat P2",')
a('                NameEn = "Cat P2"')
a('            });')
a('')
a('            foreach (var (unitCost, qty) in usages)')
a('            {')
a('                var cpId = Guid.NewGuid();')
a('                db.CostParameters.Add(new CostParameter')
a('                {')
a('                    Id = cpId,')
a('                    CategoryId = catId,')
a('                    Key = $"param-{cpId:N}",')
a('                    Label = "Test Param",')
a('                    Unit = "unit",')
a('                    Value = unitCost,')
a('                    UpdatedAt = DateTime.UtcNow')
a('                });')
a('                supplyUsagesMap[cpId.ToString()] = qty;')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        var req = new CreateMaterialRequest(')
a('            Name: $"Mat-P2-{Guid.NewGuid():N}",')
a('            CategoryId: catId,')
a('            SizeLabel: null,')
a('            WidthCm: null,')
a('            HeightCm: null,')
a('            WeightGrams: null,')
a('            StockQuantity: 0,')
a('            SupplyUsages: supplyUsagesMap')
a('        );')
a('')
a('        var resp = await client.PostAsJsonAsync("/api/v1/admin/materials", req);')
a('        if (!resp.IsSuccessStatusCode) return false;')
a('')
a('        var dto = await resp.Content.ReadFromJsonAsync<MaterialDto>();')
a('        if (dto is null) return false;')
a('')
a('        var expectedBaseCost = dto.SupplyUsages.Sum(u => u.UnitCost * u.Quantity);')
a('        return dto.BaseCost == expectedBaseCost;')
a('    }')
a('')
# Property 3 - pure unit test
a('    // Feature: material-supply-cost-model, Property 3: Full price formula holds for any valid variant inputs')
a('    // Validates: Requirements 4.1, 4.2, 4.3, 4.4')
a('    [Fact]')
a('    public void Property3_FullPriceFormulaHoldsForAnyValidVariantInputs()')
a('    {')
a('        var db = CreateInMemoryDb(nameof(Property3_FullPriceFormulaHoldsForAnyValidVariantInputs));')
a('        var svc = CreatePricingService(db);')
a('')
a('        var pairGen =')
a('            from baseCost in NonNegCostGen')
a('            from qty in NonNegCostGen')
a('            select (baseCost, qty);')
a('')
a('        var gen =')
a('            from usages in Gen.Choose(0, 3).SelectMany(n => pairGen.ListOf(n))')
a('            from minutes in ManufactureTimeGen')
a('            from electricRate in ElectricRateGen')
a('            from profit in NonNegCostGen')
a('            from taxRate in TaxRateGen')
a('            select (usages, minutes, electricRate, profit, taxRate);')
a('')
a('        Prop.ForAll(Arb.From(gen), tuple =>')
a('        {')
a('            var (usages, minutes, electricRate, profit, taxRate) = tuple;')
a('')
a('            var variantBaseCost = svc.ComputeVariantBaseCost(')
a('                usages.Select(u => (u.baseCost, u.qty)),')
a('                minutes,')
a('                electricRate);')
a('')
a('            var price = svc.ComputePrice(variantBaseCost, profit, taxRate);')
a('')
a('            var expectedBaseCost = usages.Sum(u => u.baseCost * u.qty)')
a('                + (decimal)minutes / 60m * electricRate;')
a('            var expectedPrice = (expectedBaseCost + profit) * (1 + taxRate);')
a('')
a('            return variantBaseCost == expectedBaseCost && price == expectedPrice;')
a('        })')
a('        .QuickCheckThrowOnFailure();')
a('')
a('        // Empty usages + no manufacture time = 0')
a('        Assert.Equal(0m, svc.ComputeVariantBaseCost([], null, 0m));')
a('    }')
a('')
# Property 4 - integration test (replace-all semantics)
a('    // Feature: material-supply-cost-model, Property 4: Replace-all semantics for usage persistence')
a('    // Validates: Requirements 1.2, 3.2')
a('    [Property(MaxTest = 20)]')
a('    public Property Property4_ReplaceAllSemanticsForUsagePersistence()')
a('    {')
a('        var countGen = Gen.Choose(1, 3);')
a('        return Prop.ForAll(')
a('            Arb.From(countGen),')
a('            Arb.From(countGen),')
a('            (countA, countB) => RunProperty4Async(countA, countB).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty4Async(int countA, int countB)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid materialId = Guid.Empty;')
a('        var cpIdsA = new List<Guid>();')
a('        var cpIdsB = new List<Guid>();')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p4-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('')
a('            for (int i = 0; i < countA + countB; i++)')
a('            {')
a('                var cpId = Guid.NewGuid();')
a('                db.CostParameters.Add(new CostParameter')
a('                {')
a('                    Id = cpId, CategoryId = catId,')
a('                    Key = $"p4-param-{cpId:N}", Label = "P", Unit = "u",')
a('                    Value = 1.0m, UpdatedAt = DateTime.UtcNow')
a('                });')
a('                if (i < countA) cpIdsA.Add(cpId);')
a('                else cpIdsB.Add(cpId);')
a('            }')
a('')
a('            materialId = Guid.NewGuid();')
a('            db.Materials.Add(new Material')
a('            {')
a('                Id = materialId, Name = $"Mat-P4-{materialId:N}",')
a('                CategoryId = catId, BaseCost = 0m, CreatedAt = DateTime.UtcNow')
a('            });')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // PUT with map A')
a('        var mapA = cpIdsA.ToDictionary(id => id.ToString(), _ => 1.0m);')
a('        var putA = await client.PutAsJsonAsync($"/api/v1/admin/materials/{materialId}",')
a('            new UpdateMaterialRequest(null, null, null, null, null, null, null, mapA));')
a('        if (!putA.IsSuccessStatusCode) return false;')
a('')
a('        // PUT with map B (replaces A)')
a('        var mapB = cpIdsB.ToDictionary(id => id.ToString(), _ => 2.0m);')
a('        var putB = await client.PutAsJsonAsync($"/api/v1/admin/materials/{materialId}",')
a('            new UpdateMaterialRequest(null, null, null, null, null, null, null, mapB));')
a('        if (!putB.IsSuccessStatusCode) return false;')
a('')
a('        // Verify DB has exactly map B rows')
a('        bool dbOk = false;')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            var usages = await db.MaterialSupplyUsages')
a('                .Where(u => u.MaterialId == materialId)')
a('                .ToListAsync();')
a('')
a('            var actualIds = usages.Select(u => u.CostParameterId).OrderBy(x => x).ToList();')
a('            var expectedIds = cpIdsB.OrderBy(x => x).ToList();')
a('            dbOk = actualIds.SequenceEqual(expectedIds)')
a('                && usages.All(u => u.Quantity == 2.0m);')
a('            await Task.CompletedTask;')
a('        });')
a('')
a('        if (!dbOk) return false;')
a('')
a('        // ---- Variant side ----')
a('        Guid prodId = Guid.Empty;')
a('        Guid variantId = Guid.Empty;')
a('        var matIdsA = new List<Guid>();')
a('        var matIdsB = new List<Guid>();')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            prodId = Guid.NewGuid();')
a('            db.Products.Add(new Product')
a('            {')
a('                Id = prodId, CategoryId = catId, Slug = $"p4-prod-{prodId:N}",')
a('                TitleEs = "P", TitleEn = "P", DescriptionEs = "D", DescriptionEn = "D",')
a('                Tags = [], ImageUrls = [], IsActive = true, CreatedAt = DateTime.UtcNow')
a('            });')
a('')
a('            for (int i = 0; i < countA + countB; i++)')
a('            {')
a('                var mId = Guid.NewGuid();')
a('                db.Materials.Add(new Material')
a('                {')
a('                    Id = mId, Name = $"Mat-P4v-{mId:N}",')
a('                    CategoryId = catId, BaseCost = 1.0m, CreatedAt = DateTime.UtcNow')
a('                });')
a('                if (i < countA) matIdsA.Add(mId);')
a('                else matIdsB.Add(mId);')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        var createVariant = await client.PostAsJsonAsync($"/api/v1/admin/products/{prodId}/variants",')
a('            new CreateVariantRequest')
a('            {')
a('                LabelEs = "V", Sku = $"SKU-P4-{Guid.NewGuid():N}",')
a('                Price = 0m, IsAvailable = true,')
a('                MaterialUsages = matIdsA.ToDictionary(id => id.ToString(), _ => 1.0m)')
a('            });')
a('        if (createVariant.StatusCode != System.Net.HttpStatusCode.Created) return false;')
a('        var createdVariant = await createVariant.Content.ReadFromJsonAsync<ProductVariantDto>();')
a('        if (createdVariant is null) return false;')
a('        variantId = createdVariant.Id;')
a('')
a('        // PUT variant with map B')
a('        var putVariantB = await client.PutAsJsonAsync($"/api/v1/admin/products/{prodId}/variants/{variantId}",')
a('            new UpdateVariantRequest')
a('            {')
a('                MaterialUsages = matIdsB.ToDictionary(id => id.ToString(), _ => 3.0m)')
a('            });')
a('        if (!putVariantB.IsSuccessStatusCode) return false;')
a('')
a('        // Verify via GET response that MaterialUsages == map B')
a('        var getProduct = await client.GetAsync($"/api/v1/admin/products/{prodId}");')
a('        if (!getProduct.IsSuccessStatusCode) return false;')
a('        var productDto = await getProduct.Content.ReadFromJsonAsync<ProductDetailDto>();')
a('        if (productDto is null) return false;')
a('        var variantDto = productDto.Variants.FirstOrDefault(v => v.Id == variantId);')
a('        if (variantDto is null) return false;')
a('')
a('        var actualMatIds = variantDto.MaterialUsages.Keys.Select(Guid.Parse).OrderBy(x => x).ToList();')
a('        var expectedMatIds = matIdsB.OrderBy(x => x).ToList();')
a('        return actualMatIds.SequenceEqual(expectedMatIds)')
a('            && variantDto.MaterialUsages.Values.All(q => q == 3.0m);')
a('    }')
a('')
# Property 5 - integration test (non-positive quantities rejected)
a('    // Feature: material-supply-cost-model, Property 5: Non-positive quantities are always rejected')
a('    // Validates: Requirements 1.4, 3.4')
a('    [Property(MaxTest = 20)]')
a('    public Property Property5_NonPositiveQuantitiesAreAlwaysRejected()')
a('    {')
a('        var nonPosGen = Gen.Choose(-10000, 0).Select(i => (decimal)i / 100m);')
a('        return Prop.ForAll(')
a('            Arb.From(nonPosGen),')
a('            qty => RunProperty5Async(qty).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty5Async(decimal qty)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid cpId = Guid.Empty;')
a('        Guid matId = Guid.Empty;')
a('        Guid prodId = Guid.Empty;')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p5-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('            cpId = Guid.NewGuid();')
a('            db.CostParameters.Add(new CostParameter')
a('            {')
a('                Id = cpId, CategoryId = catId, Key = $"p5-{cpId:N}",')
a('                Label = "P", Unit = "u", Value = 1.0m, UpdatedAt = DateTime.UtcNow')
a('            });')
a('            matId = Guid.NewGuid();')
a('            db.Materials.Add(new Material')
a('            {')
a('                Id = matId, Name = $"Mat-P5-{matId:N}",')
a('                CategoryId = catId, BaseCost = 1.0m, CreatedAt = DateTime.UtcNow')
a('            });')
a('            prodId = Guid.NewGuid();')
a('            db.Products.Add(new Product')
a('            {')
a('                Id = prodId, CategoryId = catId, Slug = $"p5-prod-{prodId:N}",')
a('                TitleEs = "P", TitleEn = "P", DescriptionEs = "D", DescriptionEn = "D",')
a('                Tags = [], ImageUrls = [], IsActive = true, CreatedAt = DateTime.UtcNow')
a('            });')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // POST material with non-positive quantity -> expect 400')
a('        var matResp = await client.PostAsJsonAsync("/api/v1/admin/materials",')
a('            new CreateMaterialRequest(')
a('                Name: $"Mat-P5-bad-{Guid.NewGuid():N}",')
a('                CategoryId: catId,')
a('                SizeLabel: null, WidthCm: null, HeightCm: null, WeightGrams: null,')
a('                StockQuantity: 0,')
a('                SupplyUsages: new Dictionary<string, decimal> { [cpId.ToString()] = qty }')
a('            ));')
a('        if (matResp.StatusCode != System.Net.HttpStatusCode.BadRequest) return false;')
a('')
a('        // POST variant with non-positive quantity -> expect 400')
a('        var varResp = await client.PostAsJsonAsync($"/api/v1/admin/products/{prodId}/variants",')
a('            new CreateVariantRequest')
a('            {')
a('                LabelEs = "V", Sku = $"SKU-P5-{Guid.NewGuid():N}",')
a('                Price = 0m, IsAvailable = true,')
a('                MaterialUsages = new Dictionary<string, decimal> { [matId.ToString()] = qty }')
a('            });')
a('        return varResp.StatusCode == System.Net.HttpStatusCode.BadRequest;')
a('    }')
a('')
# Property 6 - integration test (unknown reference IDs rejected)
a('    // Feature: material-supply-cost-model, Property 6: Unknown reference IDs are always rejected')
a('    // Validates: Requirements 1.3, 3.3')
a('    [Property(MaxTest = 20)]')
a('    public Property Property6_UnknownReferenceIDsAreAlwaysRejected()')
a('    {')
a('        return Prop.ForAll(')
a('            Arb.From(Gen.Constant(true)),')
a('            _ => RunProperty6Async().GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty6Async()')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid prodId = Guid.Empty;')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p6-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('            prodId = Guid.NewGuid();')
a('            db.Products.Add(new Product')
a('            {')
a('                Id = prodId, CategoryId = catId, Slug = $"p6-prod-{prodId:N}",')
a('                TitleEs = "P", TitleEn = "P", DescriptionEs = "D", DescriptionEn = "D",')
a('                Tags = [], ImageUrls = [], IsActive = true, CreatedAt = DateTime.UtcNow')
a('            });')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        var unknownCpId = Guid.NewGuid();')
a('        var matResp = await client.PostAsJsonAsync("/api/v1/admin/materials",')
a('            new CreateMaterialRequest(')
a('                Name: $"Mat-P6-{Guid.NewGuid():N}",')
a('                CategoryId: catId,')
a('                SizeLabel: null, WidthCm: null, HeightCm: null, WeightGrams: null,')
a('                StockQuantity: 0,')
a('                SupplyUsages: new Dictionary<string, decimal> { [unknownCpId.ToString()] = 1.0m }')
a('            ));')
a('        if (matResp.StatusCode != System.Net.HttpStatusCode.BadRequest) return false;')
a('')
a('        var unknownMatId = Guid.NewGuid();')
a('        var varResp = await client.PostAsJsonAsync($"/api/v1/admin/products/{prodId}/variants",')
a('            new CreateVariantRequest')
a('            {')
a('                LabelEs = "V", Sku = $"SKU-P6-{Guid.NewGuid():N}",')
a('                Price = 0m, IsAvailable = true,')
a('                MaterialUsages = new Dictionary<string, decimal> { [unknownMatId.ToString()] = 1.0m }')
a('            });')
a('        return varResp.StatusCode == System.Net.HttpStatusCode.BadRequest;')
a('    }')
a('')
# Property 7 - integration test (cascade delete)
a('    // Feature: material-supply-cost-model, Property 7: Cascade delete removes all child usage rows')
a('    // Validates: Requirements 1.5, 3.5')
a('    [Property(MaxTest = 20)]')
a('    public Property Property7_CascadeDeleteRemovesAllChildUsageRows()')
a('    {')
a('        var nGen = Gen.Choose(1, 5);')
a('        return Prop.ForAll(')
a('            Arb.From(nGen),')
a('            n => RunProperty7Async(n).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty7Async(int n)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid materialId = Guid.Empty;')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p7-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('')
a('            materialId = Guid.NewGuid();')
a('            db.Materials.Add(new Material')
a('            {')
a('                Id = materialId, Name = $"Mat-P7-{materialId:N}",')
a('                CategoryId = catId, BaseCost = 0m, CreatedAt = DateTime.UtcNow')
a('            });')
a('')
a('            for (int i = 0; i < n; i++)')
a('            {')
a('                var cpId = Guid.NewGuid();')
a('                db.CostParameters.Add(new CostParameter')
a('                {')
a('                    Id = cpId, CategoryId = catId, Key = $"p7-cp-{cpId:N}",')
a('                    Label = "P", Unit = "u", Value = 1.0m, UpdatedAt = DateTime.UtcNow')
a('                });')
a('                db.MaterialSupplyUsages.Add(new MaterialSupplyUsage')
a('                {')
a('                    Id = Guid.NewGuid(), MaterialId = materialId,')
a('                    CostParameterId = cpId, Quantity = 1.0m')
a('                });')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // DELETE material')
a('        var delResp = await client.DeleteAsync($"/api/v1/admin/materials/{materialId}");')
a('        if (!delResp.IsSuccessStatusCode) return false;')
a('')
a('        // Verify MaterialSupplyUsages count == 0 for that materialId')
a('        int usageCount = -1;')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            usageCount = await db.MaterialSupplyUsages')
a('                .CountAsync(u => u.MaterialId == materialId);')
a('            await Task.CompletedTask;')
a('        });')
a('        if (usageCount != 0) return false;')
a('')
a('        // ---- Variant side ----')
a('        Guid prodId = Guid.Empty;')
a('        Guid variantId = Guid.Empty;')
a('        Guid matForVariant = Guid.Empty;')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            matForVariant = Guid.NewGuid();')
a('            db.Materials.Add(new Material')
a('            {')
a('                Id = matForVariant, Name = $"Mat-P7v-{matForVariant:N}",')
a('                CategoryId = catId, BaseCost = 1.0m, CreatedAt = DateTime.UtcNow')
a('            });')
a('            prodId = Guid.NewGuid();')
a('            db.Products.Add(new Product')
a('            {')
a('                Id = prodId, CategoryId = catId, Slug = $"p7-prod-{prodId:N}",')
a('                TitleEs = "P", TitleEn = "P", DescriptionEs = "D", DescriptionEn = "D",')
a('                Tags = [], ImageUrls = [], IsActive = true, CreatedAt = DateTime.UtcNow')
a('            });')
a('            variantId = Guid.NewGuid();')
a('            db.ProductVariants.Add(new ProductVariant')
a('            {')
a('                Id = variantId, ProductId = prodId, Sku = $"SKU-P7-{variantId:N}",')
a('                LabelEs = "V", Price = 0m, IsAvailable = true')
a('            });')
a('            for (int i = 0; i < n; i++)')
a('            {')
a('                db.VariantMaterialUsages.Add(new VariantMaterialUsage')
a('                {')
a('                    Id = Guid.NewGuid(), VariantId = variantId,')
a('                    MaterialId = matForVariant, Quantity = 1.0m')
a('                });')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // DELETE variant')
a('        var delVariantResp = await client.DeleteAsync($"/api/v1/admin/products/{prodId}/variants/{variantId}");')
a('        if (!delVariantResp.IsSuccessStatusCode) return false;')
a('')
a('        // Verify VariantMaterialUsages count == 0 for that variantId')
a('        int varUsageCount = -1;')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            varUsageCount = await db.VariantMaterialUsages')
a('                .CountAsync(u => u.VariantId == variantId);')
a('            await Task.CompletedTask;')
a('        });')
a('        return varUsageCount == 0;')
a('    }')
a('')
# Property 8 - pure unit test (stock service)
a('    // Feature: material-supply-cost-model, Property 8: Variant stock is in-stock iff all material stock quantities are positive')
a('    // Validates: Requirements 11.2, 11.3, 11.4, 11.5')
a('    [Fact]')
a('    public void Property8_VariantStockIsInStockIffAllMaterialStockQuantitiesArePositive()')
a('    {')
a('        var stockService = new StockService();')
a('')
a('        var gen = Gen.Choose(0, 10).SelectMany(n =>')
a('            Gen.Choose(0, 100).ListOf(n));')
a('')
a('        Prop.ForAll(Arb.From(gen), quantities =>')
a('        {')
a('            var expected = quantities.Count == 0 || quantities.All(q => q > 0);')
a('            var actual = stockService.IsVariantInStock(quantities);')
a('            return actual == expected;')
a('        })')
a('        .QuickCheckThrowOnFailure();')
a('')
a('        // Edge cases')
a('        Assert.True(stockService.IsVariantInStock([]));')
a('        Assert.True(stockService.IsVariantInStock([1, 2, 3]));')
a('        Assert.False(stockService.IsVariantInStock([1, 0, 3]));')
a('        Assert.False(stockService.IsVariantInStock([0]));')
a('    }')
a('')
# Property 9 - integration test (CostParameter update propagates)
a('    // Feature: material-supply-cost-model, Property 9: CostParameter update propagates to all referencing materials')
a('    // Validates: Requirement 2.2')
a('    [Property(MaxTest = 20)]')
a('    public Property Property9_CostParameterUpdatePropagatestoAllReferencingMaterials()')
a('    {')
a('        var nGen = Gen.Choose(1, 5);')
a('        var valueGen = PosCostGen;')
a('        return Prop.ForAll(')
a('            Arb.From(nGen),')
a('            Arb.From(valueGen),')
a('            (n, newValue) => RunProperty9Async(n, newValue).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty9Async(int n, decimal newValue)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid cpId = Guid.Empty;')
a('        var materialIds = new List<Guid>();')
a('        const string cpKey = "p9-param";')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p9-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('')
a('            cpId = Guid.NewGuid();')
a('            db.CostParameters.Add(new CostParameter')
a('            {')
a('                Id = cpId, CategoryId = catId, Key = cpKey,')
a('                Label = "P9 Param", Unit = "u", Value = 1.0m, UpdatedAt = DateTime.UtcNow')
a('            });')
a('')
a('            for (int i = 0; i < n; i++)')
a('            {')
a('                var matId = Guid.NewGuid();')
a('                materialIds.Add(matId);')
a('                db.Materials.Add(new Material')
a('                {')
a('                    Id = matId, Name = $"Mat-P9-{matId:N}",')
a('                    CategoryId = catId, BaseCost = 0m, CreatedAt = DateTime.UtcNow')
a('                });')
a('                db.MaterialSupplyUsages.Add(new MaterialSupplyUsage')
a('                {')
a('                    Id = Guid.NewGuid(), MaterialId = matId,')
a('                    CostParameterId = cpId, Quantity = 1.0m')
a('                });')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // PUT new value for the CostParameter')
a('        var putResp = await client.PutAsJsonAsync($"/api/v1/admin/cost-parameters/{catId}/{cpKey}",')
a('            new UpsertCostParameterRequest("P9 Param", "u", newValue));')
a('        if (!putResp.IsSuccessStatusCode) return false;')
a('')
a('        // Verify each material BaseCost == newValue (quantity=1.0 * newValue)')
a('        foreach (var matId in materialIds)')
a('        {')
a('            var getResp = await client.GetAsync($"/api/v1/admin/materials/{matId}");')
a('            if (!getResp.IsSuccessStatusCode) return false;')
a('            var dto = await getResp.Content.ReadFromJsonAsync<MaterialDto>();')
a('            if (dto is null || dto.BaseCost != newValue) return false;')
a('        }')
a('        return true;')
a('    }')
a('')
# Property 10 - integration test (delete material referenced by variant rejected)
a('    // Feature: material-supply-cost-model, Property 10: Deleting a material referenced by a variant is always rejected')
a('    // Validates: Requirements 1.6, 10.5')
a('    [Property(MaxTest = 20)]')
a('    public Property Property10_DeletingMaterialReferencedByVariantIsAlwaysRejected()')
a('    {')
a('        var nGen = Gen.Choose(1, 5);')
a('        return Prop.ForAll(')
a('            Arb.From(nGen),')
a('            n => RunProperty10Async(n).GetAwaiter().GetResult()');
a('        );')
a('    }')
a('')
a('    private static async Task<bool> RunProperty10Async(int n)')
a('    {')
a('        await using var factory = new FilamorfosisWebFactory();')
a('        var client = await AdminPropertyTests.LoginAsAdminAsync(factory);')
a('')
a('        Guid catId = Guid.Empty;')
a('        Guid materialId = Guid.Empty;')
a('')
a('        await factory.SeedAsync(async db =>')
a('        {')
a('            catId = Guid.NewGuid();')
a('            db.Categories.Add(new Category { Id = catId, Slug = $"p10-cat-{catId:N}", NameEs = "C", NameEn = "C" });')
a('')
a('            materialId = Guid.NewGuid();')
a('            db.Materials.Add(new Material')
a('            {')
a('                Id = materialId, Name = $"Mat-P10-{materialId:N}",')
a('                CategoryId = catId, BaseCost = 1.0m, CreatedAt = DateTime.UtcNow')
a('            });')
a('')
a('            var prodId = Guid.NewGuid();')
a('            db.Products.Add(new Product')
a('            {')
a('                Id = prodId, CategoryId = catId, Slug = $"p10-prod-{prodId:N}",')
a('                TitleEs = "P", TitleEn = "P", DescriptionEs = "D", DescriptionEn = "D",')
a('                Tags = [], ImageUrls = [], IsActive = true, CreatedAt = DateTime.UtcNow')
a('            });')
a('')
a('            for (int i = 0; i < n; i++)')
a('            {')
a('                var variantId = Guid.NewGuid();')
a('                db.ProductVariants.Add(new ProductVariant')
a('                {')
a('                    Id = variantId, ProductId = prodId, Sku = $"SKU-P10-{variantId:N}",')
a('                    LabelEs = "V", Price = 0m, IsAvailable = true')
a('                });')
a('                db.VariantMaterialUsages.Add(new VariantMaterialUsage')
a('                {')
a('                    Id = Guid.NewGuid(), VariantId = variantId,')
a('                    MaterialId = materialId, Quantity = 1.0m')
a('                });')
a('            }')
a('            await db.SaveChangesAsync();')
a('        });')
a('')
a('        // DELETE material -> expect 409')
a('        var delResp = await client.DeleteAsync($"/api/v1/admin/materials/{materialId}");')
a('        return delResp.StatusCode == System.Net.HttpStatusCode.Conflict;')
a('    }')
a('}')
a('')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))
print('Written', len(L), 'lines to', OUT)
